#!/usr/bin/env bash
# vps-init 模块：一键 DD 重装（全自动续跑）
#
# 原理（bin456789/reinstall 官方机制）：
#   --ci            使用带 cloud-init 的 cloud image
#   --cloud-data    把 user-data 打包进 initrd → 新系统首启自动执行
#   --ssh-key       重装时注入公钥（新系统 root 直接密钥登录，无需密码）
#   --ssh-port      新系统 SSH 端口
# user-data = cloud-config（write_files 写 BBR 配置 + runcmd 执行 base64 内嵌的
# 自包含初始化脚本：时区/locale/BBR/装包/建用户+sudo+密钥/SSH/UFW/Fail2Ban）。
# 密码以 sha-512 哈希注入（不落明文到 /var/lib/cloud）。
#
# 限制：alpine/arch/gentoo 等不支持 cloud-init 的发行版自动降级为
#       「注入密钥+端口，重启后手动 vps-init」模式。

# 支持 --ci（cloud image）的发行版（reinstall.sh 源码 5033 行确认；debian/ubuntu 最稳）
CI_SUPPORTED_DISTROS="debian ubuntu kali rocky almalinux oracle anolis opencloudos openeuler fedora opensuse centos"

# 生成 sha-512 密码哈希（python3 → mkpasswd → openssl passwd -6）
hash_password() {  # $1=明文密码 → stdout 哈希
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "import crypt,sys; print(crypt.crypt(sys.argv[1], crypt.mksalt(crypt.METHOD_SHA512)))" "$1" 2>/dev/null && return 0
  fi
  if command -v mkpasswd >/dev/null 2>&1; then
    mkpasswd -m sha-512 "$1" && return 0
  fi
  if command -v openssl >/dev/null 2>&1 && openssl passwd -6 -help >/dev/null 2>&1; then
    openssl passwd -6 "$1" && return 0
  fi
  return 1
}

# 渲染自包含初始化脚本（新系统首启执行；占位符 __X__ 替换）
render_cloud_init_script() {  # $1=user $2=pass_hash $3=pubkey $4=ssh_port
  local user="$1" pass_hash="$2" pubkey="$3" ssh_port="$4"
  local tpl
  tpl="$(cat <<'INIT_EOF'
#!/bin/bash
# Generated by vps-init dd (cloud-init runcmd) — 新系统首次启动自动执行
set -e
log() { echo "[vps-init-cloud] $*" >&2; }

# 1. 时区 + locale
timedatectl set-timezone Asia/Shanghai 2>/dev/null || true
command -v update-locale >/dev/null 2>&1 && update-locale LANG=en_US.UTF-8 2>/dev/null || true

# 2. BBR（write_files 已落 /etc/sysctl.d/99-vps-init-bbr.conf）
sysctl --system >/dev/null 2>&1 || sysctl -p >/dev/null 2>&1 || true

# 3. 装包
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq 2>/dev/null || true
apt-get install -y -qq ufw fail2ban 2>/dev/null || true

# 4. 创建普通用户 + sudo + 密钥（__USER__）
if ! id __USER__ >/dev/null 2>&1; then
  SGROUP=""
  grep -q '^sudo:' /etc/group 2>/dev/null && SGROUP=sudo
  grep -q '^wheel:' /etc/group 2>/dev/null && SGROUP=wheel
  if [ -n "$SGROUP" ]; then
    useradd -m -s /bin/bash __USER__
    echo "__USER__:__USER_PASS_HASH__" | chpasswd -e
    usermod -aG "$SGROUP" __USER__
    mkdir -p /home/__USER__/.ssh
    echo "__PUBKEY__" > /home/__USER__/.ssh/authorized_keys
    chmod 700 /home/__USER__/.ssh
    chmod 600 /home/__USER__/.ssh/authorized_keys
    chown -R __USER__:__USER__ /home/__USER__/.ssh
    log "created user __USER__ (sudo group: $SGROUP)"
  else
    log "WARN: no sudo/wheel group, skip user creation"
  fi
fi

# 5. root 密钥（保险：reinstall --ssh-key 之外再确保）
mkdir -p /root/.ssh
grep -qF "__PUBKEY__" /root/.ssh/authorized_keys 2>/dev/null || echo "__PUBKEY__" >> /root/.ssh/authorized_keys
chmod 700 /root/.ssh; chmod 600 /root/.ssh/authorized_keys

# 6. SSH drop-in：端口 + 禁密码
mkdir -p /etc/ssh/sshd_config.d
printf 'Port __SSH_PORT__\nPasswordAuthentication no\n' > /etc/ssh/sshd_config.d/50-vps-init.conf
sshd -t 2>/dev/null && { systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true; }

# 7. UFW（--force 防无 TTY 卡死）
ufw --force enable >/dev/null 2>&1 || true
ufw default deny incoming >/dev/null 2>&1 || true
ufw default allow outgoing >/dev/null 2>&1 || true
ufw allow __SSH_PORT__/tcp >/dev/null 2>&1 || true

# 8. Fail2Ban（backend 动态探测）
BACKEND=systemd; [ -f /var/log/auth.log ] && BACKEND=auto
printf '[DEFAULT]\nignoreip = 127.0.0.1/8 ::1\nbantime = 1d\nfindtime = 10m\nmaxretry = 5\nbackend = %s\nbantime.increment = true\nbantime.maxtime = 5w\nbanaction = ufw\n\n[sshd]\nenabled = true\nport = __SSH_PORT__\nmode = aggressive\n' "$BACKEND" > /etc/fail2ban/jail.local
systemctl enable --now fail2ban >/dev/null 2>&1 || systemctl restart fail2ban 2>/dev/null || true

log "vps-init cloud-init initialization done (ssh port __SSH_PORT__)"
INIT_EOF
)"
  # 占位符替换（哈希可能含 / 与 $，用 | 分隔符并转义 &）
  printf '%s' "$tpl" | sed -e "s|__USER__|${user}|g" \
      -e "s|__USER_PASS_HASH__|${pass_hash}|g" \
      -e "s|__PUBKEY__|${pubkey}|g" \
      -e "s|__SSH_PORT__|${ssh_port}|g"
}

# 渲染 cloud-config user-data（write_files + runcmd base64）
render_cloud_config() {  # $1=init_script 内容（已渲染）
  local init_b64
  init_b64="$(printf '%s' "$1" | base64 -w0)"
  cat <<EOF
#cloud-config
write_files:
  - path: /etc/sysctl.d/99-vps-init-bbr.conf
    content: |
      net.core.default_qdisc=fq
      net.ipv4.tcp_congestion_control=bbr
runcmd:
  - [bash, -c, "printf '%s' ${init_b64} | base64 -d > /tmp/vps-init-cloud.sh && bash /tmp/vps-init-cloud.sh"]
EOF
}

dd_main() {
  local distro="" version="" ssh_port="" user="" pass="" pubkey="" pubkey_file=""

  # ---------- 命令行参数（脚本化预填） ----------
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --distro)   distro="$2"; shift 2 ;;
      --version)  version="$2"; shift 2 ;;
      --port)     ssh_port="$2"; shift 2 ;;
      --user)     user="$2"; shift 2 ;;
      --pubkey)   pubkey_file="$2"; shift 2 ;;
      *) log_warn "未知参数: $1（--distro/--version/--port/--user/--pubkey）"; shift ;;
    esac
  done

  # ---------- 交互输入 ----------
  [[ -z "$distro" ]] && { read_input "发行版（默认 debian）: " distro || distro=""; }
  [[ -z "$distro" ]] && distro="debian"
  [[ -z "$version" ]] && { read_input "版本（debian 默认 13）: " version || version=""; }
  [[ -z "$version" ]] && version="13"
  [[ -z "$ssh_port" ]] && { read_input "新系统 SSH 端口（回车随机生成）: " ssh_port || ssh_port=""; }
  [[ -z "$ssh_port" ]] && ssh_port="$(random_port)"
  [[ -z "$user" ]] && { read_input "普通用户名（默认 admin）: " user || user=""; }
  [[ -z "$user" ]] && user="admin"
  if [[ -z "$pass" ]]; then
    read_input "${user} 的密码（sudo 提权）: " pass || { log_err "无交互终端，无法设置密码"; return 1; }
  fi
  if [[ -z "$pubkey" ]]; then
    if [[ -n "$pubkey_file" && -f "$pubkey_file" ]]; then
      pubkey="$(tr -d '\r\n' < "$pubkey_file")"
    else
      read_input "SSH 公钥（粘贴，或 --pubkey <文件>）: " pubkey || { log_err "无交互终端且未提供公钥"; return 1; }
    fi
  fi
  if ! [[ "$pubkey" =~ ^ssh-(ed25519|rsa|ecdsa|dss)[[:space:]]+ ]]; then
    log_err "公钥格式不合法"
    return 1
  fi

  # ---------- 密码哈希 ----------
  local pass_hash=""
  pass_hash="$(hash_password "$pass")" || { log_err "无法生成密码哈希（需 python3/mkpasswd/openssl）"; return 1; }

  # ---------- cloud-init 支持检测 ----------
  local ci_supported=0
  if [[ " $CI_SUPPORTED_DISTROS " == *" $distro "* ]]; then
    ci_supported=1
  fi
  if [[ "$ci_supported" -eq 0 ]]; then
    log_warn "发行版 ${distro} 不支持 --ci（cloud-init），降级为：注入密钥+端口，重启后手动 vps-init"
  fi

  # ---------- 双重确认 ----------
  log_warn "================================================================"
  log_warn "即将一键 DD 重装！磁盘将完全清空，不可恢复！"
  log_warn "  发行版: ${distro} ${version}"
  log_warn "  SSH 端口: ${ssh_port}"
  log_warn "  普通用户: ${user}"
  log_warn "  全自动续跑: $([[ $ci_supported -eq 1 ]] && echo '是（cloud-init）' || echo '否（降级半自动）')"
  log_warn "================================================================"
  local ans=""
  read_input "输入 YES 确认执行: " ans || { log_warn "已取消"; return 1; }
  [[ "$ans" != "YES" ]] && { log_warn "已取消（输入 YES 才执行）"; return 1; }

  # ---------- 下载 reinstall.sh（双源自动切换） ----------
  local workdir
  workdir="$(mktemp -d /tmp/vps-init-dd.XXXXXX)" || return 1
  cd "$workdir" || return 1
  log_info "下载 reinstall.sh（国外源）..."
  if ! curl -fsSL --max-time 60 -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh; then
    log_warn "国外源失败，切换国内镜像（cnb.cool）..."
    if ! curl -fsSL --max-time 60 -O https://cnb.cool/bin456789/reinstall/-/git/raw/main/reinstall.sh; then
      log_err "reinstall.sh 下载失败（双源均不可用）"
      rm -rf "$workdir"
      return 1
    fi
  fi

  # ---------- 生成 user-data ----------
  local init_script user_data
  init_script="$(render_cloud_init_script "$user" "$pass_hash" "$pubkey" "$ssh_port")"
  if [[ "$ci_supported" -eq 1 ]]; then
    user_data="$(render_cloud_config "$init_script")"
    printf '%s\n' "$user_data" > "${workdir}/user-data"
    log_info "已生成 user-data（cloud-init 自包含初始化，密码为 sha-512 哈希）"
  fi

  # ---------- 执行 reinstall ----------
  local cmd=(bash reinstall.sh "$distro" "$version")
  if [[ "$ci_supported" -eq 1 ]]; then
    cmd+=(--ci --cloud-data "$workdir")
  fi
  cmd+=(--username root --ssh-key "$pubkey" --ssh-port "$ssh_port")

  log_info "执行: ${cmd[*]}"
  "${cmd[@]}"

  log_warn "DD 已启动。安装期间可查看 reinstall 输出；完成后系统自动重启。"
  log_warn "重启后（约 5-15 分钟）用密钥登录新系统:"
  log_warn "    ssh -p ${ssh_port} root@<服务器IP>"
  log_warn "初始化将由 cloud-init 自动完成（时区/BBR/用户/SSH/UFW/Fail2Ban）。"
  if [[ "$ci_supported" -eq 0 ]]; then
    log_warn "⚠️ 本发行版不支持自动续跑，重启后请手动: vps-init"
  fi
}
